name: Trigger auto deployment for transport-policy-miner

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/transport-policy-miner-AutoDeployTrigger-807fce7f-785b-430f-bbea-e0604df2e5eb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TRANSPORTPOLICYMINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TRANSPORTPOLICYMINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TRANSPORTPOLICYMINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: transportpolicyminer.azurecr.io
          registryUsername: ${{ secrets.TRANSPORTPOLICYMINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TRANSPORTPOLICYMINER_REGISTRY_PASSWORD }}
          containerAppName: transport-policy-miner
          resourceGroup: ndc-tracker
          imageToBuild: transportpolicyminer.azurecr.io/transport-policy-miner:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


